### ISSUE TITLE
SyntaxError: Unexpected token =  | joinMonster(  ... options = {}) {

### ISSUE THREAD

**Issue by yourse1f-yourorg** [stems/join-monster-demo#3]
yourself@yours:~/projects$ git clone git@github.com:stems/join-monster-demo.git
	Cloning into 'join-monster-demo'...
	remote: Counting objects: 110, done.
	remote: Total 110 (delta 0), reused 0 (delta 0), pack-reused 110
	Receiving objects: 100% (110/110), 37.80 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (60/60), done.
	Checking connectivity... done.
	yourself@yours:~/projects$ cd join-monster-demo/
	yourself@yours:~/projects/join-monster-demo$ npm --version
	4.1.1
	yourself@yours:~/projects/join-monster-demo$ node --version
	v4.7.0
	yourself@yours:~/projects/join-monster-demo$ lsb_release -a
	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 16.04.1 LTS
	Release:	16.04
	Codename:	xenial
	yourself@yours:~/projects/join-monster-demo$ npm install
	npm WARN deprecated node-uuid@1.4.7: use uuid module instead
	npm WARN prefer global marked@0.3.6 should be installed with -g

	> sqlite3@3.1.8 install /home/yourself/projects/join-monster-demo/node_modules/sqlite3
	> node-pre-gyp install --fallback-to-build

	[sqlite3] Success: "/home/yourself/projects/join-monster-demo/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node" is installed via remote
	join-monster-demo@1.0.0 /home/yourself/projects/join-monster-demo
	├─┬ babel-cli@6.22.2 
	│ ├─┬ babel-core@6.22.1 
	│ │ ├─┬ babel-code-frame@6.22.0 
         :           : 
         :           : 
         :           : 
	      │ ├── string_decoder@0.10.31 
	      │ └── util-deprecate@1.0.2 
	      └── uid-number@0.0.6 

	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
	yourself@yours:~/projects/join-monster-demo$ npm start

	> join-monster-demo@1.0.0 start /home/yourself/projects/join-monster-demo
	> babel-node server.js

	/home/yourself/projects/join-monster-demo/node_modules/join-monster/dist/index.js:33
	function joinMonster(resolveInfo, context, dbCall, options = {}) {
		                                                   ^

	SyntaxError: Unexpected token =
	    at exports.runInThisContext (vm.js:53:16)
	    at Module._compile (module.js:373:25)
	    at Module._extensions..js (module.js:416:10)
	    at Object.require.extensions.(anonymous function) [as .js] (/home/yourself/projects/join-monster-demo/node_modules/babel-register/lib/node.js:152:7)
	    at Module.load (module.js:343:32)
	    at Function.Module._load (module.js:300:12)
	    at Module.require (module.js:353:17)
	    at require (internal/module.js:12:17)
	    at Object.<anonymous> (/home/yourself/projects/join-monster-demo/schema-basic/QueryRoot.js:19:1)
	    at Module._compile (module.js:409:26)

	npm ERR! Linux 4.4.0-59-generic
	npm ERR! argv "/usr/bin/nodejs" "/home/yourself/.npm-global/bin/npm" "start"
	npm ERR! node v4.7.0
	npm ERR! npm  v4.1.1
	npm ERR! code ELIFECYCLE
	npm ERR! join-monster-demo@1.0.0 start: `babel-node server.js`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the join-monster-demo@1.0.0 start script 'babel-node server.js'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the join-monster-demo package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     babel-node server.js
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs join-monster-demo
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls join-monster-demo
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/yourself/projects/join-monster-demo/npm-debug.log
	yourself@yours:~/projects/join-monster-demo$

**Comment by yourse1f-yourorg** [comment]
Hmmm : 

       "engines": {
         "node": ">=6.0.0"
       },

Pity!  Can't use it then!
